[project]
name = "sky-engine"
version = "0.0.2"
description = "A wrapper around Pygame that makes it easier to use."
readme = "README.md"
requires-python = ">=3.14"
license = "MIT"
authors = [{ name = "iNCOHESiONS", email = "incohesions@gmail.com" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.basedpyright]
typeCheckingMode = "all"
pythonVersion = "3.14"

reportAny = false
reportExplicitAny = false
reportImportCycles = false  # handled by `if TYPE_CHECKING`, which basedpyright can't detect, apparently
reportUnannotatedClassAttribute = false
reportUnusedCallResult = false

[tool.poetry]
packages = [{ include = "sky" }]
repository = "https://github.com/incohesions/sky-engine"
homepage = "https://github.com/incohesions/sky-engine"

keywords = [
  "pygame",
  "game-development",
  "game-engine",
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python",
]

[tool.poetry.dependencies]
pygame-ce = "^2.5.3"
python = "^3.14"
pywin32 = [
  { version = "^311", markers = "sys_platform == 'win32'" },
]
screeninfo = "^0.8.1"
singleton-decorator = "==1.0.0"
watchdog = "6.0.0"  # for hcr and live reloading modules


[tool.ruff]
preview = true
line-length = 120

[tool.ruff.lint]
exclude = ["examples/**", "*_test.py"]
select = ["ALL"]
extend-select = [
    "C4",
    "E",
    "F",
    "FURB",
    "I",
    "ICN",
    "ISC",
    "NPY",
    "PTH",
    "RET",
    "SIM",
    "TC",
    "TD",
    "TID",
    "UP",
    "W",
]
ignore = [
    "any-type",
    "blank-line-after-function",
    "docstring-extraneous-exception",
    "docstring-missing-exception",
    "docstring-starts-with-this",
    "empty-method-without-abstract-decorator",
    "error-instead-of-exception",
    "escape-sequence-in-docstring",
    "f-string-in-exception",
    "incorrect-blank-line-before-class",
    "invalid-todo-tag",
    "line-contains-fixme",
    "logging-f-string",
    "missing-blank-line-after-last-section",
    "missing-copyright-notice",
    "missing-todo-author",
    "missing-todo-link",
    "multi-line-summary-first-line",
    "no-self-use",
    "non-empty-init-module",
    "non-imperative-mood",
    "overload-with-docstring",
    "raise-vanilla-args",
    "raise-vanilla-args",
    "raw-string-in-exception",
    "suspicious-non-cryptographic-random-usage",
    "too-many-public-methods",
    "undocumented-magic-method",
    "undocumented-public-init",
]

[tool.ruff.lint.isort]
lines-between-types = 1
lines-after-imports = 2

[tool.ruff.format]
docstring-code-format = true
